# scripts/map2sym.py
import sys
import re

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 map2sym.py <map_file> > ksyms_data.c")
        return

    map_file = sys.argv[1]
    
    print("// AUTO-GENERATED BY map2sym.py")
    print('#include "kernel/ksyms.h"')
    print("")
    print("const struct kernel_symbol kernel_symbols[] = {")

    count = 0
    with open(map_file, 'r') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 3:
                addr = parts[0]
                type_char = parts[1].upper()
                name = parts[2]
                
                if type_char == 'T' or type_char == 't':
                    if "." in name: continue
                    
                    print(f'    {{ 0x{addr}, "{name}" }},')
                    count += 1

    print("    { 0xFFFFFFFFFFFFFFFF, 0 } // Sentinel")
    print("};")
    print(f"const uint32_t kernel_symbol_count = {count};")

if __name__ == "__main__":
    main()